In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [31]:
df = pd.read_csv("spam.csv", encoding="latin-1")

In [13]:
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [14]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [15]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [16]:
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [17]:
df

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,1
5568,ham,Will Ì_ b going to esplanade fr home?,0
5569,ham,"Pity, * was in mood for that. So...any other s...",0
5570,ham,The guy did some bitching but I acted like i'd...,0


In [18]:
new_df = pd.read_csv('spam.csv')

In [19]:
new_df['Category'].replace({'ham':0,'spam':1},inplace=True)

In [20]:
new_df.head()

,Category,Message
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [22]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [24]:
df.shape

(5572, 3)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.25)

In [28]:
X_test.shape

(1393,)

#### Create bag of words representation using CountVectorizer

In [60]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [ ]:
X_train

909     January Male Sale! Hot Gay chat now cheaper, c...
3482    Hello, my love! How goes that day ? I wish you...
5441    By the way, make sure u get train to worc fore...
4054    When is school starting. Where will you stay. ...
1787                           Yes:)sura in sun tv.:)lol.
                              ...                        
4873                     Wat happened to the cruise thing
1722    Thought praps you meant another one. Goodo! I'...
1266      \Hey sorry I didntgive ya a a bellearlier hunny
3419    As a valued customer, I am pleased to advise y...
3123    My uncles in Atlanta. Wish you guys a great se...
Name: Message, Length: 4179, dtype: object

In [33]:
X_train_cv

<4179x7555 sparse matrix of type '<class 'numpy.int64'>'
	with 55639 stored elements in Compressed Sparse Row format>

In [34]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
X_train_cv.shape

(4179, 7555)

In [ ]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'âªt', 'âªve', 'â¼1'], dtype=object)

In [37]:
v.get_feature_names_out()[1221]

'batt'

In [38]:
v.vocabulary_

{'january': 3683,
 'male': 4211,
 'sale': 5731,
 'hot': 3411,
 'gay': 3017,
 'chat': 1709,
 'now': 4715,
 'cheaper': 1715,
 'call': 1572,
 '08709222922': 88,
 'national': 4575,
 'rate': 5421,
 'from': 2952,
 '5p': 548,
 'min': 4360,
 'cheap': 1714,
 'to': 6755,
 '8p': 702,
 'peak': 4996,
 'stop': 6321,
 'texts': 6622,
 '08712460324': 105,
 '10p': 259,
 'hello': 3308,
 'my': 4541,
 'love': 4108,
 'how': 3422,
 'goes': 3092,
 'that': 6637,
 'day': 2135,
 'wish': 7351,
 'your': 7517,
 'well': 7269,
 'and': 939,
 'fine': 2795,
 'babe': 1159,
 'hope': 3392,
 'you': 7511,
 'find': 2792,
 'some': 6129,
 'job': 3718,
 'prospects': 5319,
 'miss': 4388,
 'boytoy': 1441,
 'teasing': 6571,
 'kiss': 3837,
 'by': 1553,
 'the': 6643,
 'way': 7229,
 'make': 4204,
 'sure': 6449,
 'get': 3044,
 'train': 6830,
 'worc': 7396,
 'foregate': 2875,
 'street': 6339,
 'not': 4704,
 'shrub': 5973,
 'hill': 3340,
 'have': 3267,
 'fun': 2970,
 'night': 4650,
 'when': 7295,
 'is': 3633,
 'school': 5781,
 'starting'

In [39]:
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
np.where(X_train_np[0]!=0)

(array([  88,  105,  259,  548,  702, 1572, 1709, 1714, 1715, 2952, 3017,
        3411, 3683, 4211, 4360, 4575, 4715, 4996, 5421, 5731, 6321, 6622,
        6755], dtype=int64),)

#### Naive Bayes Classifier

In [42]:
model = MultinomialNB()

In [43]:
model.fit(X_train_cv,y_train)

MultinomialNB()

In [46]:
y_pred = model.predict(X_test_cv)

In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1214
           1       0.97      0.93      0.95       179

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



#### Test on random datapoint

In [52]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [53]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1], dtype=int64)